### ISSUE TITLE
BUG: Switching between network options adds multiple Vultiservers

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1028]
**Describe the bug**
When switching between network options multiple times, it let's the Vultiserver join multiple times

**To Reproduce**
1. Go to `active vault`
2. switch between network options on `pair screen`
3. See error

**Expected behavior**
Vultiserver joins only once

**Screenshots**
![image](https://github.com/user-attachments/assets/43c52061-2919-45ab-b3a6-e792f87d3e60)

**Comment by johnnyluo** [comment]
for fastvault / active vault , let's disable "local" mode.
