### ISSUE TITLE
ADD: Scroll indication if content is hidden below

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1038]
User does not have indication if content is below the screen and therefore does not know that he needs to scroll.

Implement scroll indication that user knows that content is eblow, e.g. in `verify screen` for initiating device

**Comment by yevhen1sec** [comment]
This is my low performance test device and it's not release app version
So not freak out user experience will be much smoother 

So as you can see it's not very smoothly and it's alredy affecting performance a bit

https://github.com/user-attachments/assets/f5f27403-51e1-4c61-a5cc-28e3428a6628

**Comment by yevhen1sec** [comment]
as we agreed with @realpaaao 
issue will be closed
In future will be implemented by google https://developer.android.com/jetpack/androidx/compose-roadmap
