### ISSUE TITLE
Calculate Polkadot Chain Gas Fee

### ISSUE THREAD

**Issue by aminsato** [vultisig/vultisig-android#1083]
The dafualt Gas value for Polkadot Chain  is zero
https://github.com/vultisig/vultisig-android/blob/ce57a021ba5ad3e3e6cbbf8dd993b293e732aa34/data/src/main/kotlin/com/vultisig/wallet/data/repositories/GasFeeRepository.kt#L103-L111

**Comment by johnnyluo** [comment]
as far as I understand, we don't specify how much fee we will be paying when send a polkadot transaction , the network caculate the fee and charge it automatically. 

However , on IOS, there is `static let defaultFeeInPlancks: BigInt = 250_000_000` , which will be used to calculate the max value user can send
