### ISSUE TITLE
[BUG] wrong error message

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1093]
**Describe the bug**
When swapping funds I occasionally get wrong error messages. Even though the swap went through, the pairing device received "not sufficient funds" error

**Expected behavior**
Be consistent if swap goes through or has an error in both devices

**Screenshots**
![Image](https://github.com/user-attachments/assets/0419ff23-2b23-43bd-808f-7a7bf38543d7)

-v25

**Additional context**
Also the error is confusing for the user, please update that the error has our error UI standard according to figma.

![Image](https://github.com/user-attachments/assets/367a46cc-ef4c-4df7-80ec-d3953da0cd57)

**Comment by yevhen1sec** [comment]
fixed by #1199 pt
