### ISSUE TITLE
[BUG] SOL balance updating

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1095]
**Describe the bug**
Users reported that SOL balances are not updating and threrefore they are unable to send funds and are stuck.

**Expected behavior**
Balances updating consistently

**Screenshots**
![Image](https://github.com/user-attachments/assets/ba650f00-e11c-4b85-a01d-71e53a404547)

 - Version 25

**Comment by realpaaao** [comment]
@vultisig/android @johnnyluo I narrowed it down that only special vaults are affected.

**Comment by realpaaao** [comment]
Further update that if vault is imported into iOS the balance load and can be accessed.

**Comment by johnnyluo** [comment]
I think this one probably already fixed by #1098

**Comment by realpaaao** [comment]
QA done. with RPC change it updates
