### ISSUE TITLE
[IMPROVE] Error message display

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1101]
Currently Keysign errors (swap or send) get displayed in a confusing and unpleasant way for the user. 

Example:
![Image](https://github.com/user-attachments/assets/3320fd5f-c233-41a2-8efe-a9b51d8b0c9b)

Please please display each error in our error standard and simplyfy the error that the user understands.

Example above:

![Image](https://github.com/user-attachments/assets/a3986782-1384-4c27-a5d4-ff0e4ebce5b0)

**Comment by yevhen1sec** [comment]
All known Keysign errors (swap or send) get displayed in a simple and understandable way for the user.
