### ISSUE TITLE
[BUG] USDT.ARB does not have value

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1169]
**Describe the bug**
Having USDT on aRB in the wallet does not give any value

**Screenshots**
![Image](https://github.com/user-attachments/assets/79a2bfb0-3503-4fcd-afb9-fbee346fbcbc)

 - Version 29

**Comment by aminsato** [comment]
@realpaaao I'm unable to reproduce the issue. Perhaps using a VPN might help. Alternatively, could you please provide me with your Arbitrum address?

**Comment by realpaaao** [comment]
QA done.
