### ISSUE TITLE
[BUG] unable to send BTC

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1172]
**Describe the bug**
It is not possible to send out BTC atm due to missing or bad UTXO management.

**To Reproduce**
1. Try sending BTC
2. See error

**Expected behavior**
Able to send BTC no matter what size and UTXO

**Screenshots**
![Image](https://github.com/user-attachments/assets/3a44f427-4223-4a94-8ab9-68d4f08a7582)

 - Version 29

**Additional context**
It says not enough UTXOs even though just a small part of the balance is sent and there are UTXO to spent.

**Comment by realpaaao** [comment]
@aminsato please also verify LTC and DOGE, all UTXO.

**Comment by aminsato** [comment]
@realpaaao 
I checked it agains btc
https://mempool.space/tx/7c161d2b76f0694478d0ce66735db99b6c0175d26e194c28a292f5cdfc0f0667

Doge
https://blockchair.com/dogecoin/transaction/2960c3975a06ae2096ba28e073b7f221cdef2b6959e1086144b9dd92fd09d7bf

Bitcoin cash
https://blockchair.com/bitcoin-cash/transaction/a51805d714963f6c07b7475cce87b7934bc1a43402bbf740e222cc9407aa659f

**Comment by realpaaao** [comment]
Fixed in v30

**Comment by realpaaao** [comment]
Closing
