### ISSUE TITLE
[BUG] Not able to swap between EVM

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1174]
**Describe the bug**
Swapping between EVM chains is not possible as the error "Source and desitnation assets can't be the same" gets promptes

**To Reproduce**
1. Go to swap page
2. Select two EVM assets
3. See error

**Expected behavior**
able to swap EVM chains

**Screenshots**
![Image](https://github.com/user-attachments/assets/58ba11d7-827e-4fab-9256-0eea09d84a61)

 - Version 29

**Comment by johnnyluo** [comment]
duplicate of #1137

**Comment by realpaaao** [comment]
Closing
