### ISSUE TITLE
[BUG] unable to swap from ETH.ARB to RUNE

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1177]
**Describe the bug**
When trying to sign swap from ETH.ARB to RUNE the keysign is not possible

**Expected behavior**
Able to swap over this route

**Screenshots**
![Image](https://github.com/user-attachments/assets/15c4f2e0-1e15-4cb9-81ed-6a88c12782d3)

 - Version 29

**Comment by johnnyluo** [comment]
https://github.com/vultisig/vultisig-android/blob/main/app/src/main/java/com/vultisig/wallet/ui/models/swap/SwapFormViewModel.kt#L272
for Mayaswap , we should use `quote.data.inboundAddress` ,  currently can't deal with `quote.data.router`

**Comment by realpaaao** [comment]
QA done.
