### ISSUE TITLE
[BUG] unable to join keygen with windows

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1216]
**Describe the bug**
When initiating keygen it is impossible to join with android

**To Reproduce**
1. initiate keygen on windows
2. join with android
3. See error

**Expected behavior**
Able to join keygen

**Screenshots**
![Image](https://github.com/user-attachments/assets/0591f85a-b663-49c2-902e-718b6e152e19)

 - Version 1.0.30

**Comment by johnnyluo** [comment]
As mentioned yesterday , because android didn't do a URL encoding , already fixed on windows part , so close this one for now
