### ISSUE TITLE
[BUG] No value for USDC on ARB on swap screen

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1236]
**Describe the bug**
When swapping to ARB.USDC it does not reflect any value in Fiat.

**Expected behavior**
Display Dollar (fiat) value

**Screenshots**
![Image](https://github.com/user-attachments/assets/50c70f28-7c09-4d50-8813-f42d4c18c478)

 - Version v30

**Comment by aminsato** [comment]
can't be reproduced
