### ISSUE TITLE
[Question]: Why not Satochip support?

### ISSUE THREAD

**Issue by Sami32** [vultisig/vultisig-android#1331]
Why did you added Tapsigner support and not Satochip which is FOSS and boasts a lifetime warranty?

https://github.com/toporin

Edit:
And have an EAL6+ Secure Element
https://satochip.io/product/seedkeeper/
Coud it be related to multisig co-signing ability?

**Comment by johnnyluo** [comment]
not relevant

**Comment by Sami32** [comment]
I just discovered that you are on the way to sell your proprietary hardware wallet so i guess that could explain why?
