### ISSUE TITLE
BUG: Can't swap on android 14

### ISSUE THREAD

**Issue by LongCX** [vultisig/vultisig-android#1332]
**Describe the bug**
Can't swap any asset

**To Reproduce**
1. Go to asset any
2. Click on button swap
3. Chosen asset to swap
4. Chosen amount
5. See error: Invalid amount

**Expected behavior**
Can swap

**Screenshots**
![Screenshot_20241111-094651_Vultisig](https://github.com/user-attachments/assets/59a01d3f-04e1-460c-92d3-579396c3355d)

**Smartphone
 - Device: Redmi K60
 - OS: Android 14
 - Version app: 1.0.32

**Comment by aminsato** [comment]
@LongCX Can't reporduce it
