### ISSUE TITLE
[BUG] Switch to the matching vault when scanning a  tx QR code with a mismatch vault

### ISSUE THREAD

**Issue by aminsato** [vultisig/vultisig-android#1391]
Previously, scanning a  tx QR code with a mismatched vault would automatically search for the correct vault and, if found, sign it. However, it now displays the error message: "Wrong vault selected."

**Comment by yevhen1sec** [comment]
https://github.com/vultisig/vultisig-android/issues/1293

**Comment by aminsato** [comment]
@yevhen1sec , this is different from [#1293](https://github.com/vultisig/vultisig-android/issues/1293). It should search for the correct value part, and if it finds the correct one, it must sign the transaction. Otherwise, it should show an incorrect value.

**Comment by yevhen1sec** [comment]
@aminsato "For the user it is confusing if he can sign tx with another vault selected."

**Comment by aminsato** [comment]
> @aminsato "For the user it is confusing if he can sign tx with another vault selected."

Okay cool
