### ISSUE TITLE
[BUG] $RENDER on SOL without price

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1463]
**Describe the bug**
The token $RENDER shows correct balance but no price.

**Expected behavior**
Also display its price correctly

**Comment by biotq23DE** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Vultisig Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Stopstilhen** [comment]
@realpaaao 
Kindly add pull request 
And ignore the post with link… it’s a scam

**Comment by aminsato** [comment]
@realpaaao 
Can't be reporduce

https://github.com/user-attachments/assets/de576354-6c32-44ce-bb25-9949bb5f4283

**Comment by realpaaao** [comment]
Closing, not reproducable
