### ISSUE TITLE
ADD: visual feedback while waiting on keygen steps to complete

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#216]
Please add visual feedback while waiting on keygen steps to complete. 
At the moment while waiting it is not clear if screen froze or vault is created.
We could add small pusating waves in the ring or changingcolors.

- [ ] Ring dosen't complete after `success step` without animation

https://github.com/vultisig/vultisig-android/assets/167348323/a53afc23-be41-4a0b-9ebf-b16e8b474a34

**Comment by YGolybev** [comment]
@realpaaao, it would be great to have a Figma design of what we should implement

**Comment by realpaaao** [comment]
@YGolybev Figma will be updated. Could we use the same buffering dots as in signing view?

![image](https://github.com/vultisig/vultisig-android/assets/167348323/7a7b891d-7c79-479b-b81a-2d25d11569e6)

**Comment by YGolybev** [comment]
@realpaaao yes
