### ISSUE TITLE
ADD: Possibility to select all assets on swap page

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#217]
At the moment only the selected Chain can be send on sending screen.

Desired:
able to select all assets to send from this view.

![image](https://github.com/vultisig/vultisig-android/assets/167348323/2ea01112-7243-4b21-b43c-79341c3aaae0)

**Comment by YGolybev** [comment]
@realpaaao it would be great to have a Figma design of what to implement. As this feature currently is not available in iOS or Figma.

**Comment by realpaaao** [comment]
@YGolybev see in figma under `send`- view.
logic: cache all coins with asset balance to be selectable
![image](https://github.com/vultisig/vultisig-android/assets/167348323/bd053d37-ea9c-4c12-be80-a77d92e48ebc)

**Comment by YGolybev** [comment]
@realpaaao Currently, the iOS app loads all tokens from the vault on the Send screen. 

I think the reason for that is that sometimes we can't have any cached balance (e.g., a user is in the app for the first time, and we can't load the balance in time until he gets to the "Send" screen), or the balance may be updated while we're on the screen.

So, we can either show all tokens as in iOS (and maybe show their balance near them?) or add a loading indication and add only tokens with the known balance to this list.

What do you think?

**Comment by realpaaao** [comment]
@YGolybev I think it would be best to first match with iOS to show all tokens selected from the vault. But with showing the balance near them the screen gets too cramped, so it is sufficient that user sees balance of selected token.
