### ISSUE TITLE
BUG: Deleting Vault closes App

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#219]
BUG: when deleting a vault the app closes and need to be reopend.

Desired: App switchs to next available vault or to Vault Add Screen.

**Comment by YGolybev** [comment]
@realpaaao, I can't reproduce the issue. If I delete a vault, it either switches to the next one, or if it's the last vault, it just shows an empty vault accounts screen, but it doesn't close. Can you please provide a screencast of a bug?

**Comment by johnnyluo** [comment]
I fixed it in https://github.com/vultisig/vultisig-android/pull/246
