### ISSUE TITLE
BUG: FAQs missing answers

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#220]
BUG: FAQ dropdowns can't be opened.

Desired: Please add dropdown answers from [FAQ](https://vultisig.com/faq.html)

![image](https://github.com/vultisig/vultisig-android/assets/167348323/555b57d8-9384-4a7e-b6da-e4b975dbdfc6)

**Comment by YGolybev** [comment]
Duplicate of #167 @aminsato
