### ISSUE TITLE
iPhone can't read Send transaction QR code

### ISSUE THREAD

**Issue by yvebe** [vultisig/vultisig-android#228]
User reports:
Creating Transaction:

Starting a send transaction on the iPhone, confirming on Android - successful.
Starting a send transaction on Android, confirming on iPhone - Getting ERROR saying "Wrong Vault or Pair Device".

Definitely have the right vault selected.

**Comment by johnnyluo** [comment]
This could because IOS is not on the latest version

**Comment by johnnyluo** [comment]
this has been fixed in https://github.com/vultisig/vultisig-android/pull/269
