### ISSUE TITLE
ADD: Export/Import Session ID 

### ISSUE THREAD

**Issue by GrassRootsCrypto** [vultisig/vultisig-android#243]
**Is your feature request related to a problem? Please describe.**
I am creating a new wallet and I have to use my phone's camera to get the session ID - join a wallet. 
For testing I am running two Android Devices in an emulator so using the camera is not possible. 
![image](https://github.com/vultisig/vultisig-android/assets/40199525/86e8f991-3d60-4cec-b999-789b26652606)

**Describe the solution you'd like**
The ability to save the session ID for future reference or import it into another wallet without giving the app camera permission. 
Like how you can export a 2FA code, the use it to import into another device. 

**Describe alternatives you've considered**
Sign in to Google and expose my pers details to do testing, not doing it. 

**Additional context**

**Comment by YGolybev** [comment]
@GrassRootsCrypto @realpaaao seems like that would be solved by #241, am I right?

**Comment by realpaaao** [comment]
Agree, maybe we can add the option to share as `session ID` or `QR code` ?

**Comment by YGolybev** [comment]
@realpaaao The session ID seems insufficient for pairing; we can share information as a deep link, though I'm not sure if it will work as a URL in the current state, but it will be text

**Comment by realpaaao** [comment]
I think easiest to implement is just QR code sharing, which will also resolve this issue.

**Comment by GrassRootsCrypto** [comment]
> @GrassRootsCrypto @realpaaao seems like that would be solved by #241, am I right?

Whatever allows me to create a wallet without having to use the camera to scan the QR code. A way to share text or something between devices.
