### ISSUE TITLE
[ADD] Keygen ERROR screen 

### ISSUE THREAD

**Issue by johnnyluo** [vultisig/vultisig-android#26]
Keygen error screen , it should looks like the following
<img width="146" alt="image" src="https://github.com/voltix-vault/voltix-android/assets/749608/85f22e8e-c7a3-4db7-ade5-2a326575bd1e">

In KeygenFlowView , when `KeygenState.ERROR` , use this new view
The screen is available in figma as well

**Comment by LF0044** [comment]
Doing it now.

**Comment by LF0044** [comment]
Concluded.
