### ISSUE TITLE
BUG: Display of Icons 

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#263]
**Describe the bug**
Some images of the coins are not formatted correctly or don't load:

Polygon:
- [ ] WETH doesn't load

ETH:
- [ ] LINK icon needs to be circle
- [ ] TGT icon needs to be circle

BASE: 
- [ ] ETH has BASE and ETH icon stacked 

AVAX:
- [ ] AVAX icon is displayed as ETH

ARB:
- [ ] ETH and ARB token have ARB and ETH ICON stacked 
- [ ] Correct image for ARB
- [ ] TGT icon needs to be circle

BLAST:
- [ ] ETH and WETH missing image

OP:
- [ ] ETH has OP and ETH icon stacked

CRO:
- [ ] CRO has ETH icon stacked

MATIC:
- [ ] MATIC Coin missing
- [ ] WETH image not loading

SOL:
- [ ] SOL icon needs to be circle

Screenshots:
![image](https://github.com/vultisig/vultisig-android/assets/167348323/3bbb2998-5e9f-4c82-a186-b2faef7b4f41)
![image](https://github.com/vultisig/vultisig-android/assets/167348323/fbdd68f5-5e9f-4f25-ad5b-9b5e76d8de45)
![image](https://github.com/vultisig/vultisig-android/assets/167348323/c9791f72-aca5-4fd8-81df-dddfe0b11d09)
![image](https://github.com/vultisig/vultisig-android/assets/167348323/d11b6484-01b1-4000-a5ac-9549cada3c44)

**Comment by aminsato** [comment]
> MATIC:
> 
> * [ ]  MATIC Coin missing

Regarding the "MATIC Coin missing" issue:

The default icon for MATIC on ETH chain is Polygon.
For Wrapped MATIC , the defaul icon is:
![image](https://github.com/vultisig/vultisig-android/assets/32006742/f8af4713-174d-4b91-912a-f2fc0aba7705)

**Comment by realpaaao** [comment]
@aminsato see iOS for reference:
![image](https://github.com/vultisig/vultisig-android/assets/167348323/203eae62-37ac-4d16-9a6b-bb91a6e21358)
