### ISSUE TITLE
BUG: Crash with pressing burger view repeatedly

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#265]
**Describe the bug**
When pressing the burger view in top left repeatedly crashes the app or unable to exit from settings.

**To Reproduce**
1. main page
2. press burger view repeatedly
3. See error

**Screenshots**

https://github.com/vultisig/vultisig-android/assets/167348323/d0b76f3d-5c71-4919-b6d4-d3f34e7b5b46

**Comment by realpaaao** [comment]
@aminsato issue can still be repoduced. Either crashes like before or back button will stop working or random views pop up, If deleted a vault before, that vault re-appears.

**Comment by aminsato** [comment]
> @aminsato issue can still be repoduced. Either crashes like before or back button will stop working or random views pop up, If deleted a vault before, that vault re-appears.

@realpaaao Please update to the latest version and let me know if you continue to experience the problem.
