### ISSUE TITLE
BUG: Deselect chain in token view

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#266]
**Describe the bug**
The native coin is also listed and able to toggle in token view, which results in deselecting the whole chain when toggeling.

**To Reproduce**
1. Go to any chain
2. Click on `choose tokens`
3. deselect native coin

**Expected behavior**
Remove native coin in `token view`

**Screenshots**
![image](https://github.com/vultisig/vultisig-android/assets/167348323/5762f812-d8b4-4b02-8c08-1d906bc7ec48)

**Comment by YGolybev** [comment]
@realpaaao Maybe we should remove a native token from this list. (Also, maybe we should hide the "Choose tokens" button if there are no tokens (like for Bitcoin).)

**Comment by realpaaao** [comment]
@YGolybev edited issue, to remove native token from the list. 

> (Also, maybe we should hide the "Choose tokens" button if there are no tokens (like for Bitcoin)?)
Yes, as this is the case on iOS and android should mirror it.
