### ISSUE TITLE
[Fix] DeviceInfo is not showing correct tick 

### ISSUE THREAD

**Issue by johnnyluo** [vultisig/vultisig-android#27]
Currently , the device info item is using a checkbox to indicate whether it has been selected or not , refer to the following snapshot
![image](https://github.com/voltix-vault/voltix-android/assets/749608/000173fe-33a3-48b9-8d21-ee23368b0402)

It doesn't looks nice, instead it should looks like the following when selected , has a tick on the right top corner
<img width="223" alt="image" src="https://github.com/voltix-vault/voltix-android/assets/749608/fe232ec9-17ea-4f0f-a66e-acac1023590c">

**Comment by LF0044** [comment]
Doing it

**Comment by LF0044** [comment]
Finished.
Link to PR: https://github.com/vultisig/vultisig-android/pull/46
