### ISSUE TITLE
BUG: Deleting vault crashes app

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#280]
**Describe the bug**
when deleting a vault, the app crashes

**To Reproduce**
1. Go to settings
2. delete vault
3. See error

**Expected behavior**
Switching to nex available vault

**Comment by YGolybev** [comment]
@realpaaao is that a duplicate of #219 or there is some difference?

**Comment by realpaaao** [comment]
@YGolybev yes true, we didn't push a new apk. that's why I couldn't confirm. mb.

colsing due to resolved in #219.
