### ISSUE TITLE
BUG: Change Vault naming screen on Vault creation

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#297]
**Describe the bug**
When creating a vault, change the Vault naming screen to be congruent with figma and iOS.
current:
![image](https://github.com/vultisig/vultisig-android/assets/167348323/8bab4d92-e691-42f3-bc97-5bd7d6416933)

desired:
![image](https://github.com/vultisig/vultisig-android/assets/167348323/82bbb269-6dab-435a-8abb-cdbc57fbce38)

**Comment by aminsato** [comment]
Fixed in #286
