### ISSUE TITLE
BUG: Cronos chain balance not loading

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#306]
**Describe the bug**
Cronos Chain is not loading the asset balance on `home screen` and `chain detail screen`, possibly due to bad api request.

**Expected behavior**
Show balance

**Screenshots**
![image](https://github.com/vultisig/vultisig-android/assets/167348323/f0c448b6-9f58-4bdb-bc9b-961759f8fbff)

**Comment by johnnyluo** [comment]
I have cronos , and it load just fine for me ,

**Comment by johnnyluo** [comment]
Yup, user should be able to get the version from setting screen.

**Comment by realpaaao** [comment]
Yes is displayed as V1.0 (4).


But I had no possibility to reproduce this but users reported. Since yesterday it happens consistently on both of my devices...
