### ISSUE TITLE
BUG: Wrong fees on Thorchain

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#323]
Thorchain tx fees are currently set to 0.2 in the app. 

The correct fee would be 0.02 Rune but as Thorchain is switching to USD denomination for fees soon, please use the Thornode endpoint [https://thornode.ninerealms.com/thorchain/network](https://thornode.ninerealms.com/thorchain/network ) and use native_tx_fee .
Please ensure this is also applied to the "max send" button.
If you have questions please ask @enriquesouza as he implemented it already in iOS

**Comment by realpaaao** [comment]
@johnnyluo I see you already implemented in #256, when did you plan to push an update so users can interact properly?

**Comment by johnnyluo** [comment]
This has been implemented already #256
