### ISSUE TITLE
BUG: languages won't change

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#356]
**Describe the bug**
when changing languages it switches in settings but the app doesn't change the language

**To Reproduce**
1. change settings
2. See error

**Expected behavior**
changing languages

**Screenshots**
![image](https://github.com/vultisig/vultisig-android/assets/167348323/503bd852-8a84-4415-bd73-f05bfc08e7f1)

**Comment by johnnyluo** [comment]
@aminsato , we could add a few translation of the app , using google translation, currently ios support the following
1. English
2. German
3. Italian
4. Portuguese
5. Spanish
6. Croatian

**Comment by realpaaao** [comment]
@johnnyluo @aminsato we also have some community help already for further languages, see [Languages](https://discord.com/channels/1203844257220395078/1244713659972980858/1244780314098925669)
It is for iOS atm but maybe we could do the same format for android so both apps can source from there?

**Comment by aminsato** [comment]
Closed in favor of #382
