### ISSUE TITLE
ADD: TON support

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#391]
As discussed in [Discord](https://discord.com/channels/1203844257220395078/1206028132902248548/1251561319539150878) we should add TON support to our wallet. 
Please talk with @enriquesouza what will be most feasible way to implement it, as he alreadz started to investigate.

**Comment by johnnyluo** [comment]
not possible yet , need to wait until wallet core add TON support first

**Comment by realpaaao** [comment]
QA done. 
Able to receive and send funds:
https://tonscan.org/tx/2Sx8ysCCV4nr/ceJIMKiMzM8AUkJ8jYF4cC9qbFCliY=
