### ISSUE TITLE
BUG: No gas fees error, SOL

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#411]
**Describe the bug**
When  trying to send SOL, the error `no gas fees` comes up and not able to send SOL.

![image](https://github.com/vultisig/vultisig-android/assets/167348323/15f79a2d-1265-4295-89c8-f59d464e12ed)

**Comment by johnnyluo** [comment]
It works fine on my side , can you please double check whether you have access to the following link?
```
https://api.mainnet-beta.solana.com/haproxy_load
```

**Comment by johnnyluo** [comment]
Likely it failed get the priority fee ,  https://github.com/vultisig/vultisig-android/pull/415 should get it fixed

**Comment by realpaaao** [comment]
> https://api.mainnet-beta.solana.com/haproxy_load

@johnnyluo works fine
