### ISSUE TITLE
IMPROVE: Chain selection toggles

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#424]
The toggle buttons in Chain selection are really big and unappealing. 
Please change it to reflect the propotions in [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=1372-17501&t=HBPQ4XfNrBto1TiT-4)

Current:
![Uploading image.png…]()

**Comment by yevhen1sec** [comment]
fixed in #449
