### ISSUE TITLE
BUG: BSC.USDT wrong balance

### ISSUE THREAD

**Issue by panzerfly** [vultisig/vultisig-android#441]
Since it was launched the android version is not seeing my BSC.USDT balance (shows zero) where as, for the same vault, the Iphone&Mac version see the balance.

not working with android version: V1.0 (6)

**Comment by aminsato** [comment]
Thank you @panzerfly  for reporting this issue. I have checked with a different account and found no issue with BSC.USDT balances, whether zero or non-zero, on the Android version.

Could you please check your balance again? If the issue persists, please provide more details, such as your BSC address, so we can investigate further.

![USDT-0](https://github.com/vultisig/vultisig-android/assets/32006742/f0ab56b6-40ab-4fd8-95f9-64284354e5c7)
![usdt-non0](https://github.com/vultisig/vultisig-android/assets/32006742/4d6b5e85-c7ea-4fc7-8d7b-eced2da851ed)

**Comment by aminsato** [comment]
@realpaaao Could you check again too?

**Comment by realpaaao** [comment]
@aminsato also can't reprodce this error on v7.. Will monitor it though
