### ISSUE TITLE
BUG: Send screen crashes when no balance present

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#512]
**Describe the bug**
When entering `send screen ` and no balance is present it crashes on some chains like:
THORChain, Maya, DYDX, Gaia or Kujira. 

When implementing a fix, please verify that all chains are free of error.

**To Reproduce**
1. Enter send screen with no balance present
2. See error

**Expected behavior**
`Send view opens normally`

-version 8

**Comment by johnnyluo** [comment]
fixed by #514 #506
