### ISSUE TITLE
BUG: Crash on Swap page when selecting token w/o route

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#526]
**Describe the bug**
A user raised when selecting a token which has no swap route available and it gets selected, the app crashes.

**To Reproduce**
1. Go to swap view
2. Select a token
3. Select token that doesn't have swap route
4. See crash

**Expected behavior**
Please only display the swap routes which are available for the selected token in `from` field. Or just display an error which states "swap route not available"

-version 9

**Comment by aminsato** [comment]
Closed in favor of https://github.com/vultisig/vultisig-android/pull/537

**Comment by aminsato** [comment]
Closed in favor of https://github.com/vultisig/vultisig-android/pull/537
