### ISSUE TITLE
ADD: Swap view only displays tokens with balance

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#528]
At the moment the swap view is generic to all chains, leading to that when sending on a chain like ETH, all the tokens get displayed in a non interesting order.

Please implement that only tokens with balance are displayed and able to send. This can be done after #486 is implemented.

**Comment by johnnyluo** [comment]
This is not correct , for example , I don't have any USDT , but I would like to swap some RUNE to USDT, if we only display tokens with balance , then USDT won't show up on the list , I won't be able to swap it.

I still rather user add the token first , and then swap from/to it

**Comment by realpaaao** [comment]
@yvebe did we also apply #329 to swap view? If so we can close.
