### ISSUE TITLE
Use strings.xml to support better i18n

### ISSUE THREAD

**Issue by YGolybev** [vultisig/vultisig-android#53]
Currently, a lot of strings are hard-coded into `@Composables`

A common practice for managing strings and locales is [using string resources](https://developer.android.com/guide/topics/resources/string-resource)

Hard-coded ex. (current):
`text = "Vaults",`
String resources example:
`text = stringResource(R.string.vaults_title)`

We should use string ids, and store strings in strings.xml where possible. 

Also, their name structure may be ${screen_name}_${string_content}.

**Comment by johnnyluo** [comment]
We already done a sweep , just need to remember using the xml file in the future , close this for now
