### ISSUE TITLE
Add id to Vault

### ISSUE THREAD

**Issue by YGolybev** [vultisig/vultisig-android#54]
Currently, we use the Vault's field name as an ID. But if we need to build a valid URL for deep links, it won't be possible because the name can contain whitespaces. To fix this issue, we may add an ID field to the vault.

`UUID.randomUUID().toString()` can be a good fit for generating ids.

**Comment by johnnyluo** [comment]
We could use the `PubKeyECDSA` field , which is unique , and it is hex encoded

**Comment by YGolybev** [comment]
@johnnyluo looks good; thank you. Can you tell me if `PubKeyECDSA` has a size restriction? Because URLs are restricted to 2048 characters.

**Comment by YGolybev** [comment]
Closing the issue. Resolution: use `PubKeyECDSA` as a unique identifier for the vault.
