### ISSUE TITLE
BUG: QR import on keysign not possible

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#565]
**Describe the bug**
When trying to import a QR code on camera view with the gallery, nothing happens when selecting the respective QR code to join session.

**To Reproduce**
1. share QR code
2. open camera on pairing device
3. import QR over gallery icon

**Expected behavior**
pairing initiates on loading QR

- version 9

**Comment by yevhen1sec** [comment]
I have found out that this issue is related to mlkit.
Most of the time qrcode scanned correctly. But we have found an edge case.
Scanner refuses to recognise qrcode when it's borderless.
![image](https://github.com/user-attachments/assets/be246485-7b4d-47bc-8049-7eba203e85e0)
This is an exaple.
