### ISSUE TITLE
Remove Guava

### ISSUE THREAD

**Issue by yvebe** [vultisig/vultisig-android#59]
Google's Guava is a library with many utilities. But! They were helpful in Java EE a long time ago. Currently, there's little to no use in Google's Guava for Android and Kotlin, and as it is a huge library, it leaves a significant footprint on build performance and _(if ProGuard isn't set up correctly)_ application size on the device.

There's no use of Guava in a project as of now, so we may delete it.

**Comment by johnnyluo** [comment]
we use guava as cache , it has been used in `Server.kt`, which is a build in http server in the android app

But if there are better library , I am open to change it

**Comment by realpaaao** [comment]
@yvebe Do we have a better library or do we want to close that issue?
