### ISSUE TITLE
BUG: Able to proceed on swap screen without balance check

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#592]
**Describe the bug**
When selecting a swap route on swap screen it is possible to proceed even without suffcient balance of the "FROM" asset.

**Expected behavior**
Not able to send funds if not sufficient funds are available.

-version 11

**Additional context**
Pleas implement suffcient fund check on swap screen

**Comment by aminsato** [comment]
Fixed in #595
