### ISSUE TITLE
BUG: Token selection view , show vultisig embedded tokens on the top

### ISSUE THREAD

**Issue by johnnyluo** [vultisig/vultisig-android#597]
**Describe the bug**
Currently when open token selection view on ETH chain , it looks like the following
<img width="357" alt="image" src="https://github.com/user-attachments/assets/09ea41b5-9590-4938-9353-45ff581ffb47">
It show all the tokens from 1inch , please show all the tokens in `Coins.SupportedCoins`, when user start to type in "search" text field , then show the tokens from 1inch that match the search criteria

**Comment by realpaaao** [comment]
same as #525
