### ISSUE TITLE
ADD: Share vault qr code match with IOS png

### ISSUE THREAD

**Issue by yevhen1sec** [vultisig/vultisig-android#723]
![image](https://github.com/user-attachments/assets/f9c9a7ad-b29d-46bf-8306-b1d87fcff8aa)

**Comment by realpaaao** [comment]
@yevhen1sec but please keep current QR code style like you already have it. Just add Vault name and pubkeys
![image](https://github.com/user-attachments/assets/80f9d252-9c8d-4ae3-b197-da3b946365d2)
