### ISSUE TITLE
BUG: QR invoice scan not correct/possible

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#750]
**Describe the bug**
When scanning an Invoice QR code with camera the app doesn't behave well:
1. It doesn't select the correct chain or asset
2. When an amount is included in the QR the app crashes
3. Does not paste address correcty and includes prefix

**To Reproduce**
1. Scan QR Code with camera on main screen or send screen
2. See error

**Expected behavior**
The App correctly selects the chain, asset and if included price

**Screenshots**
Invoice QR
![image](https://github.com/user-attachments/assets/6e318aea-ef59-4384-8024-e2566df0cc57)

Invoice QR with amount
![image](https://github.com/user-attachments/assets/9675ba53-6f5e-477d-913e-7b5ca6e091bb)

-v15

**Comment by johnnyluo** [comment]
Please make sure the app doesn't crash on the second QR code
