### ISSUE TITLE
IMPROVE: Change EVM L2 Icons from ETH to chain icon

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#766]
Currently all EVM L2 Icons have ETH displayed with the L2 on a small circle. This is confusing for Users. 
Please change the Icons that the L2 is displayed on the big icon and ETH on the small.

![image](https://github.com/user-attachments/assets/9544ce1b-a644-40fe-bcce-5899bf3ac9f5)

**Comment by johnnyluo** [comment]
I have to disagree , if we switch around , it will be more confusing, Let's take arbitrum , I myself will think it is arbitrum on ETH chain

**Comment by realpaaao** [comment]
@johnnyluo I see your point. JP wanted to have it changed.
What do you think of just compeltely removing the ETH reference then? So Just the Arb, Blast, Base icon ? 
As everyone knows it is a ETH L2.

**Comment by yevhen1sec** [comment]
@johnnyluo @realpaaao so what is final dessicison, should I switch icons OR remove eth and put chain icon as big?

**Comment by johnnyluo** [comment]
I think this is an IOS issue , not android , android is already doing what it suppose to do

**Comment by johnnyluo** [comment]
I am going to close this one
