### ISSUE TITLE
BUG: Pressing on SPL token crashes app

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#921]
**Describe the bug**
When selecting a SPL token after starting the app, it crashes.
After the second restart you can open it.

**To Reproduce**
1. Go to Solana Chain
2. Click on a SPL token
3. See error

**Expected behavior**
Open on first time selection

-v20

**Additional context**
Looks like some caching problem

**Comment by aminsato** [comment]
Closing this issue as the crash has been resolved in PR #920
