### ISSUE TITLE
BUG: No Vault check on joining a keysign

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#959]
**Describe the bug**
It is possible to sign a transaction from any vault selected as currently the vault check is not working

**To Reproduce**
1. create tx with a vault
2. on the pairing device be on a different vault
3. scan QR
4. tx gets signed without `wrong vault` error
5. See error

**Expected behavior**
Getting the `wrong vault` error due to the verification

-v22

**Comment by realpaaao** [comment]
@yvebe I get where you are coming from. Personally I would rather have the user knowingly select the correct vault as a "approve" method before sending.
@johnnyluo what is you preference?

**Comment by johnnyluo** [comment]
Let's keep current behaviour ,  user mostly approve the transaction
